# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revaluation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revaluationdocument',
            name='stock_change_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.StockChangeSet'),
        ),
        migrations.AlterField(
            model_name='revaluationdocument',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluation_revaluationdocument_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revaluationdocument',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluation_revaluationdocument_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revaluationline',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='revaluationline',
            name='revaluation_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revaluation.RevaluationDocument'),
        ),
        migrations.AlterField(
            model_name='revaluationline',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluation_revaluationline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revaluationline',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluation_revaluationline_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
