# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revaluation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revaluationdocument',
            name='stock_change_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockChangeSet'),
        ),
        migrations.AddField(
            model_name='revaluationdocument',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_revaluationdocument_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revaluationdocument',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_revaluationdocument_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
