# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancysolution',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='stockcountdocument',
            name='stock_change_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.StockChangeSet'),
        ),
        migrations.AlterField(
            model_name='stockcountdocument',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_stockcountdocument_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockcountdocument',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_stockcountdocument_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='accounting_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.AccountingGroup'),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_count.StockCountDocument'),
        ),
        migrations.AlterField(
            model_name='temporaryarticlecount',
            name='article_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
    ]
