# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockchangeset_migrate_enum_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockchangeset',
            name='enum',
        ),
    ]
