# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stockchangeset_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchangeset',
            name='source',
            field=models.CharField(choices=[('test_do_not_use', 'Test (DO NOT USE)'), ('cash_register', 'Cash register'), ('supplication', 'Supplication'), ('rma', 'RMA'), ('internalise', 'Internalise'), ('externalise', 'Externalise'), ('revaluation', 'Revaluation'), ('stock_count', 'Stock count')], max_length=50),
        ),
    ]
