# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20170116_2203'),
        ('stock', '0006_auto_20170119_2241'),
    ]

    operations = [
    ]
