# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_merge_20170202_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='change_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.StockChangeSet'),
        ),
        migrations.AlterField(
            model_name='stocklocklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
