# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0007_orderline_copro'),
        ('supplier', '0002_auto_20160813_0229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20160810_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('copro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockWishLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('stock_wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.StockWish')),
            ],
        ),
        migrations.CreateModel(
            name='StockWishTableLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('article_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
        ),
        migrations.CreateModel(
            name='StockWishTableLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('stock_wish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.StockWish')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('order_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderLine')),
                ('supplier_article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.ArticleTypeSupplier')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.SupplierOrder')),
            ],
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='supplier_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.SupplierOrder'),
        ),
    ]
