# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ISO length should be 3.', regex='^.{3}$')])),
                ('name', models.CharField(max_length=255)),
                ('digits', models.IntegerField()),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=28)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.CurrencyData')),
            ],
        ),
        migrations.CreateModel(
            name='TestCostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestMoneyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_currency', money.models.CurrencyField(max_length=3)),
                ('money', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestOtherMoneyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_currency', money.models.CurrencyField(max_length=3)),
                ('money', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_currency', money.models.CurrencyField(max_length=3)),
                ('price_vat', money.models.VATLevelField(decimal_places=6, max_digits=15)),
                ('price', money.models.PriceField(decimal_places=5, max_digits=28, no_currency_field=True, no_vat_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSalesPriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_currency', money.models.CurrencyField(max_length=3)),
                ('price_vat', money.models.VATLevelField(decimal_places=6, max_digits=15)),
                ('price_cost', models.DecimalField(decimal_places=5, max_digits=28)),
                ('price', money.models.SalesPriceField(decimal_places=5, max_digits=28, no_cost_field=True, no_currency_field=True, no_vat_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VATPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('vatrate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.VAT')),
            ],
        ),
        migrations.AddField(
            model_name='accountinggroup',
            name='vat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.VAT'),
        ),
    ]
