# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20170128_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinggroup',
            name='vat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.VAT'),
        ),
        migrations.AlterField(
            model_name='denomination',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.CurrencyData'),
        ),
        migrations.AlterField(
            model_name='vatperiod',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.VAT'),
        ),
    ]
