# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20180123_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencydata',
            options={'default_permissions': ()},
        ),
    ]
