# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_squashed_0002_auto_20160811_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('book_value_currency', money.models.CurrencyField(max_length=3)),
                ('book_value', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('labelkey', models.IntegerField(null=True)),
                ('labeltype', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')])),
            ],
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('book_value_currency', money.models.CurrencyField(max_length=3)),
                ('book_value', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('is_in', models.BooleanField()),
                ('memo', models.CharField(max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
        ),
        migrations.CreateModel(
            name='StockChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.CharField(max_length=255, null=True)),
                ('enum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='stockchange',
            name='change_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockChangeSet'),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='labelkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='labeltype',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('labeltype', 'labelkey', 'article')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='labelkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='labeltype',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='labelkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='labeltype',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='labelkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='labeltype',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')]),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
