# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('salesprice_currency', money.models.CurrencyField(max_length=3)),
                ('salesprice_vat', money.models.VATLevelField(decimal_places=6, max_digits=8)),
                ('salesprice_cost', models.DecimalField(decimal_places=5, max_digits=28)),
                ('salesprice', money.models.SalesPriceField(decimal_places=5, max_digits=28, no_cost_field=True, no_currency_field=True, no_vat_field=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('salesprice_currency', money.models.CurrencyField(max_length=3)),
                ('salesprice_vat', money.models.VATLevelField(decimal_places=6, max_digits=8)),
                ('salesprice_cost', models.DecimalField(decimal_places=5, max_digits=28)),
                ('salesprice', money.models.SalesPriceField(decimal_places=5, max_digits=28, no_cost_field=True, no_currency_field=True, no_vat_field=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockLog')),
            ],
        ),
    ]
