# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='labelkey',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='labeltype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='labelkey',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='labeltype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
