# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='cost',
            new_name='book_value',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='cost_currency',
            new_name='book_value_currency',
        ),
        migrations.RenameField(
            model_name='stockmodification',
            old_name='cost',
            new_name='book_value',
        ),
        migrations.RenameField(
            model_name='stockmodification',
            old_name='cost_currency',
            new_name='book_value_currency',
        ),
    ]
