# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockchangeset',
            old_name='description',
            new_name='memo',
        ),
    ]
