# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 21:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='labelkey',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='labeltype',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.$')]),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='labelkey',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='labeltype',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.$')]),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('labeltype', 'labelkey', 'article')]),
        ),
    ]
