# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20160223_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockchange',
            old_name='log_entry',
            new_name='change_set',
        ),
        migrations.AddField(
            model_name='stockchange',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
