# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 21:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20160308_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='labelkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='labeltype',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')]),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='labelkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='labeltype',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')]),
        ),
    ]
