# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20160203_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
