# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20160329_2122'),
        ('stock', '0003_auto_20160402_2306'),
    ]

    operations = [
    ]
