# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 20:39
from __future__ import unicode_literals

from django.db import migrations


def migrate_enum_to_stock(apps, schema_editor):
    # The migration dict to use to migrate the data
    source_migration_dict = {
        0: "cash_register",
        1: "supplication",
        2: "rma",
        3: "internalise",
        4: "externalise",
        5: "revaluation",
        6: "stock_count"
    }

    # We can't import the StockChangeSet model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    changeset_model = apps.get_model("stock", "StockChangeSet")

    # Loop over all changesets and migrate the enum field to the source field using the migration dict
    for changeset in changeset_model.objects.all():
        changeset.source = source_migration_dict[changeset.enum]
        changeset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockchangeset_source'),
    ]

    operations = [
        migrations.RunPython(migrate_enum_to_stock),
    ]
