# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockchangeset_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockchange',
            name='memo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
