# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stockchangeset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchangeset',
            name='enum',
            field=models.IntegerField(),
        ),
    ]
