# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20160223_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockchangeset',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
