# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20160223_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockchange',
            name='date',
        ),
        migrations.AddField(
            model_name='stockchangeset',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 23, 22, 52, 49, 916545, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
