# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(editable=False, max_length=64)),
            ],
            options={
                'ordering': ['label_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LabelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_long', models.CharField(max_length=64, unique=True)),
                ('name_short', models.CharField(editable=False, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assortment.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_short', models.CharField(editable=False, max_length=32, unique=True)),
                ('type_long', models.CharField(editable=False, max_length=2, unique=True)),
                ('counting_type', models.CharField(choices=[('s', 'string'), ('n', 'decimal'), ('i', 'integer'), ('b', 'boolean')], editable=False, max_length=1)),
                ('incremental_type', models.CharField(blank=True, choices=[('SI', 'the SI standard is in powers of 1000, starting with 1000^-4: f, n, u, m, [], K, M, G, T, P, E, ...'), ('ISQ', 'the ISQ standard is in powers of 1024 (2^10), starting with 1024^0: [], Ki, Mi, Gi, Ti, Pi, Ei, ...'), ('EU', 'the EU thousands, millions and milliards `standard`'), ('US', 'the US thousands, millions and billions `standard`')], max_length=3, null=True)),
            ],
            options={
                'ordering': ['type_short', 'type_long'],
            },
        ),
        migrations.AddField(
            model_name='labeltype',
            name='unit_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='assortment.UnitType'),
        ),
        migrations.AddField(
            model_name='label',
            name='label_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='assortment.LabelType'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('value', 'label_type')]),
        ),
    ]
