# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externalise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalisedocument',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='externalise_externalisedocument_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externalisedocument',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='externalise_externalisedocument_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externaliseline',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='externaliseline',
            name='externalise_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='externalise.ExternaliseDocument'),
        ),
        migrations.AlterField(
            model_name='externaliseline',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='externalise_externaliseline_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
