# This file is a template, and might need editing before it works on your project.
image: nikolaik/python-nodejs:latest

stages:
  - install
  - test

cache:
  paths:
    - backend/.pip/
    - frontend/node_modules/
  key: "$CI_PROJECT_ID"

installDeps:
  stage: install
  script:
    - pushd frontend
    - yarn --pure-lockfile
    - popd
    - pushd backend
    - pip install --cache-dir=.pip -r requirements.txt
    - popd

testFrontendLint:
  stage: test
  cache:
    policy: pull
  script:
    - cd frontend
    - yarn lint

testFrontendUnit:
  stage: test
  cache:
    policy: pull
  script:
    - cd frontend
    - yarn --pure-lockfile
    - yarn test-once

testBackend:
  stage: test
  cache:
    policy: pull
  script:
    - cd backend
    - pip install --cache-dir=.pip -r requirements.txt
    - python3 manage.py test -k
