Swipe_SwipeTests:
  only:
    - external
  script:
    - /bin/true

Swipe_FrontendLint:
  only:
    - external
  script:
    - /bin/true

Swipe_FrontendUnitTests:
  only:
    - external
  script:
    - /bin/true
