# This file is a template, and might need editing before it works on your project.
image: nikolaik/python-nodejs:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
    - frontend/node_modules/
  key: "$CI_PROJECT_ID"

testFrontendLint:
  stage: test
  script:
    - cd frontend
    - yarn lint

testFrontendUnit:
  stage: test
  script:
    - cd frontend
    - yarn --pure-lockfile
    - yarn test-once

testBackend:
  stage: test
  script:
    - cd backend
    - pip install -r requirements.txt
    - python3 manage.py test -k
