# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_auto_20160813_0229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0004_auto_20160823_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackingDocumentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True, null=True)),
                ('packing_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplication.PackingDocument')),
                ('supplier_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.SupplierOrderLine')),
            ],
        ),
    ]
