# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20161019_1900'),
        ('supplication', '0002_auto_20160909_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('packing_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplication.PackingDocument')),
            ],
        ),
    ]
