# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:22
from __future__ import unicode_literals

import datetime

from decimal import Decimal
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vat',
            name='rate',
        ),
        migrations.AddField(
            model_name='vat',
            name='vatrate',
            field=models.DecimalField(decimal_places=6, default=Decimal("1"), max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
