# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmoneytype',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 1, 29, 10, 16, 28, 878912, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
