# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:19
from __future__ import unicode_literals

from django.db import migrations
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcosttype',
            name='money',
            field=money.models.MoneyField(decimal_places=5, default='EUR', max_digits=28, no_currency_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcosttype',
            name='money_currency',
            field=money.models.CurrencyField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
