# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_squashed_0006_accountinggroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('vatrate', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='vat',
            name='vatrate',
        ),
        migrations.AddField(
            model_name='vatperiod',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.VAT'),
        ),
    ]
