# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20160215_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vat',
            name='vatrate',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
