# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_testmoneytype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Iso Code'),
        ),
    ]
