# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 19:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_currencydata_denomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='iso',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ISO length should be 3.', regex='^.{3}$')]),
        ),
    ]
