# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20160129_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmoneytype',
            name='money_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='money.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso',
            field=models.CharField(max_length=32, verbose_name='Iso Code'),
        ),
    ]
