# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20160129_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmoneytype',
            name='money_currency',
        ),
    ]
