# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20160308_2027'),
        ('money', '0003_auto_20160215_2347'),
    ]

    operations = [
    ]
