# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('vat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.VAT')),
            ],
        ),
    ]
