# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20170127_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
    ]
