# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_invoicing', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcustinvoice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Transaction'),
        ),
        migrations.AddField(
            model_name='custominvoiceline',
            name='custom_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_invoicing.CustomCustInvoice'),
        ),
    ]
