# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_squashed_0005_person_user'),
        ('customer_invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFieldOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='crm.OrganisationTypeField')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='crm.OrganisationTypeField')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='crm.OrganisationTypeField')),
                ('email_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='crm.OrganisationTypeField')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_name', to='crm.OrganisationTypeField')),
                ('zip_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip', to='crm.OrganisationTypeField')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFieldPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='crm.PersonTypeField')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='crm.PersonTypeField')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='crm.PersonTypeField')),
                ('email_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='crm.PersonTypeField')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pers_name', to='crm.PersonTypeField')),
                ('zip_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip', to='crm.PersonTypeField')),
            ],
        ),
    ]
