# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_squashed_0005_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactorganisation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='contactorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='organisationtypefieldvalue',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='organisationtypefieldvalue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.OrganisationType', verbose_name='Organisation type'),
        ),
        migrations.AlterField(
            model_name='organisationtypefieldvalue',
            name='typefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.OrganisationTypeField', verbose_name='Organisation type field'),
        ),
        migrations.AlterField(
            model_name='persontypefieldvalue',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='persontypefieldvalue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.PersonType', verbose_name='Person type'),
        ),
        migrations.AlterField(
            model_name='persontypefieldvalue',
            name='typefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.PersonTypeField', verbose_name='Person type field'),
        ),
    ]
