# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180123_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='parent_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Organisation', verbose_name='Parent organisation'),
        ),
    ]
