# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180514_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipepermissiongroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
