# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0004_auto_20170105_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypeSupplierRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CSVSupplierRelation',
            fields=[
                ('datatypesupplierrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article_updater.DataTypeSupplierRelation')),
                ('separator', models.CharField(max_length=5)),
                ('start_at', models.IntegerField()),
                ('number', models.IntegerField()),
                ('name', models.IntegerField()),
                ('price', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('ean', models.IntegerField()),
                ('minimum_order', models.IntegerField()),
                ('packing_amount', models.IntegerField()),
            ],
            bases=('article_updater.datatypesupplierrelation',),
        ),
        migrations.CreateModel(
            name='XMLSupplierRelation',
            fields=[
                ('datatypesupplierrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article_updater.DataTypeSupplierRelation')),
                ('item_name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('supply', models.CharField(max_length=30)),
                ('ean', models.CharField(max_length=30)),
                ('minimum_order', models.CharField(max_length=30)),
                ('packing_amount', models.CharField(max_length=30)),
            ],
            bases=('article_updater.datatypesupplierrelation',),
        ),
        migrations.AddField(
            model_name='datatypesupplierrelation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
    ]
