# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_squashed_0002_auto_20160811_1947'),
        ('money', '0001_squashed_0006_accountinggroup'),
        ('stock', '0001_squashed_0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominationCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Denomination')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyInOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cash_register', models.BooleanField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.CurrencyData')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opening_count', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=28)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginTime', models.DateTimeField()),
                ('endTime', models.DateField(null=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Register')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('closing_memo', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registerperiod',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod'),
        ),
        migrations.AddField(
            model_name='registercount',
            name='register_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterPeriod'),
        ),
        migrations.AddField(
            model_name='moneyinout',
            name='register_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterPeriod'),
        ),
        migrations.AddField(
            model_name='denominationcount',
            name='register_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterCount'),
        ),
        migrations.AddField(
            model_name='moneyinout',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=28),
        ),
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registerperiod',
            name='beginTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registercount',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=28),
        ),
        migrations.AlterField(
            model_name='registercount',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=-1.0, max_digits=28),
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_cash_register',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.PaymentType'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClosingCountDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_currency', money.models.CurrencyField(max_length=3)),
                ('difference', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('sales_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningCountDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_currency', money.models.CurrencyField(max_length=3)),
                ('difference', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('register_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterCount')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', money.models.CurrencyField(max_length=3)),
                ('amount', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPeriodDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=28)),
                ('currency_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.CurrencyData')),
                ('sales_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('salesperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod')),
                ('stock_change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockChangeSet')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price_currency', money.models.CurrencyField(max_length=3)),
                ('price_vat', money.models.VATLevelField(decimal_places=6, max_digits=15)),
                ('price', money.models.PriceField(decimal_places=5, max_digits=28, no_currency_field=True, no_vat_field=True)),
                ('count', models.IntegerField()),
                ('isRefunded', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='registerperiod',
            name='memo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OtherCostTransactionLine',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.TransactionLine')),
            ],
            bases=('register.transactionline',),
        ),
        migrations.CreateModel(
            name='OtherTransactionLine',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.TransactionLine')),
            ],
            bases=('register.transactionline',),
        ),
        migrations.CreateModel(
            name='SalesTransactionLine',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.TransactionLine')),
                ('labeltype', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')])),
                ('labelkey', models.IntegerField(blank=True, null=True)),
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
            options={
                'abstract': False,
            },
            bases=('register.transactionline', models.Model),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Transaction'),
        ),
        migrations.AddField(
            model_name='payments',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Transaction'),
        ),
    ]
