# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_squashed_0008_auto_20160526_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherCostTransactionLine',
        ),
        migrations.DeleteModel(
            name='OtherTransactionLine',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SalesTransactionLine',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionLine',
        ),
    ]
