# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20160923_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
