# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20161027_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='is_invoicing',
            field=models.BooleanField(default=False),
        ),
    ]
