# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_registercount_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingcountdifference',
            name='register_count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterCount'),
        ),
    ]
