# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20170511_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingcountdifference',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.SalesPeriod'),
        ),
        migrations.AlterField(
            model_name='denominationcount',
            name='denomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.Denomination'),
        ),
        migrations.AlterField(
            model_name='denominationcount',
            name='register_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.RegisterCount'),
        ),
        migrations.AlterField(
            model_name='moneyinout',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Register'),
        ),
        migrations.AlterField(
            model_name='moneyinout',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.SalesPeriod'),
        ),
        migrations.AlterField(
            model_name='openingcountdifference',
            name='register_count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.RegisterCount'),
        ),
        migrations.AlterField(
            model_name='register',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.CurrencyData'),
        ),
        migrations.AlterField(
            model_name='register',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.PaymentType'),
        ),
        migrations.AlterField(
            model_name='registercount',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Register'),
        ),
        migrations.AlterField(
            model_name='registercount',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.SalesPeriod'),
        ),
        migrations.AlterField(
            model_name='salesperioddifference',
            name='currency_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.CurrencyData'),
        ),
        migrations.AlterField(
            model_name='salesperioddifference',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.SalesPeriod'),
        ),
    ]
