# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.VAT')),
            ],
        ),
    ]
