# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='vat',
        ),
    ]
