# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_accountinggroup'),
        ('article', '0001_squashed_0006_auto_20160602_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='accounting_group',
        ),
        migrations.AddField(
            model_name='sellabletype',
            name='accounting_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='money.AccountingGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='othercosttype',
            name='fixed_price',
            field=money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True),
        ),
        migrations.AlterField(
            model_name='othercosttype',
            name='fixed_price_currency',
            field=money.models.CurrencyField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='productcombination',
            unique_together=set([('article_type', 'and_product')]),
        ),
    ]
