# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_accountinggroup'),
        ('supplier', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_fixed_price', models.BooleanField(default=False)),
                ('fixed_price_currency', money.models.CurrencyField(max_length=3)),
                ('fixed_price_vat', money.models.VATLevelField(decimal_places=6, max_digits=8)),
                ('fixed_price_cost', models.DecimalField(decimal_places=5, max_digits=28)),
                ('fixed_price', money.models.SalesPriceField(decimal_places=5, max_digits=28, no_cost_field=True, no_currency_field=True, no_vat_field=True)),
                ('book_keeping_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.AccountingGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherCostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_fixed_price', models.BooleanField(default=False)),
                ('fixed_price_currency', money.models.CurrencyField(max_length=3)),
                ('fixed_price_vat', money.models.VATLevelField(decimal_places=6, max_digits=8)),
                ('fixed_price_cost', models.DecimalField(decimal_places=5, max_digits=28)),
                ('fixed_price', money.models.SalesPriceField(decimal_places=5, max_digits=28, no_cost_field=True, no_currency_field=True, no_vat_field=True)),
                ('book_keeping_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.AccountingGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('and_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.AndProductType')),
            ],
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='vat',
        ),
        migrations.AddField(
            model_name='articletype',
            name='book_keeping_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='money.AccountingGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='fixed_price',
            field=money.models.SalesPriceField(decimal_places=5, default=10000, max_digits=28, no_cost_field=True, no_currency_field=True, no_vat_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='fixed_price_cost',
            field=models.DecimalField(decimal_places=5, default=10000, max_digits=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='fixed_price_currency',
            field=money.models.CurrencyField(default='EUR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='fixed_price_vat',
            field=money.models.VATLevelField(decimal_places=6, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='has_fixed_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articletype',
            name='suppliers',
            field=models.ManyToManyField(to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
        ),
        migrations.AddField(
            model_name='orproducttype',
            name='article_types',
            field=models.ManyToManyField(to='article.ArticleType'),
        ),
    ]
