# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

# Due to a bug, this migration was edited by hand
class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160808_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='andproducttype',
            name='wishabletype_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.WishableType'),
            preserve_default=False,
        ),

        migrations.RemoveField(
            model_name='andproducttype',
            name='sellabletype_ptr',
        ),

    ]
