# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160422_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andproducttype',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='andproducttype',
            name='fixed_price_cost',
        ),
        migrations.RemoveField(
            model_name='andproducttype',
            name='fixed_price_currency',
        ),
        migrations.RemoveField(
            model_name='andproducttype',
            name='fixed_price_vat',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='fixed_price_cost',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='fixed_price_currency',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='fixed_price_vat',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='fixed_price_cost',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='fixed_price_currency',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='fixed_price_vat',
        ),
    ]
