# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160203_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='intf',
            field=models.IntegerField(default=2),
        ),
    ]
