# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160423_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='articletype',
            old_name='book_keeping_group',
            new_name='accounting_group',
        ),
        migrations.RemoveField(
            model_name='andproducttype',
            name='book_keeping_group',
        ),
        migrations.RemoveField(
            model_name='andproducttype',
            name='has_fixed_price',
        ),
        migrations.RemoveField(
            model_name='andproducttype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='andproducttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='has_fixed_price',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orproducttype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orproducttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='book_keeping_group',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='has_fixed_price',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='id',
        ),
        migrations.AddField(
            model_name='articletype',
            name='fixed_price',
            field=money.models.MoneyField(decimal_places=5, default=0, max_digits=28, no_currency_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='fixed_price_currency',
            field=money.models.CurrencyField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercosttype',
            name='price',
            field=money.models.MoneyField(decimal_places=5, default=0, max_digits=28, no_currency_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercosttype',
            name='price_currency',
            field=money.models.CurrencyField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SellableType',
            fields=[
                ('wishabletype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.WishableType')),
            ],
            bases=('article.wishabletype',),
        ),
        migrations.AddField(
            model_name='orproducttype',
            name='wishabletype_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.WishableType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='andproducttype',
            name='sellabletype_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.SellableType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='sellabletype_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.SellableType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercosttype',
            name='sellabletype_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.SellableType'),
            preserve_default=False,
        ),
    ]
