# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articletype_intf'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='name',
            field=models.CharField(default='HI', max_length=128),
            preserve_default=False,
        ),
    ]
