# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 21:54
from __future__ import unicode_literals

from django.db import migrations
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160526_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='suppliers',
        ),
        migrations.AlterField(
            model_name='articletype',
            name='fixed_price',
            field=money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True, null=True),
        ),
    ]
