# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20161019_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishabletype',
            name='branch',
        ),
    ]
