# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160526_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercosttype',
            old_name='price',
            new_name='fixed_price',
        ),
        migrations.RenameField(
            model_name='othercosttype',
            old_name='price_currency',
            new_name='fixed_price_currency',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='othercosttype',
            name='name',
        ),
        migrations.AddField(
            model_name='orproducttype',
            name='fixed_price',
            field=money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True, null=True),
        ),
        migrations.AddField(
            model_name='orproducttype',
            name='fixed_price_currency',
            field=money.models.CurrencyField(default='EUR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishabletype',
            name='name',
            field=models.CharField(default='Blank', max_length=255),
            preserve_default=False,
        ),
    ]
