# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articletype_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='ean',
            field=models.IntegerField(null=True),
        ),
    ]
