# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170116_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='ean',
            field=models.BigIntegerField(null=True),
        ),
    ]
