# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170126_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='serial_number',
            field=models.BooleanField(default=True),
        ),
    ]
