# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_wishabletype_branch'),
        ('article', '0008_auto_20170126_2136'),
    ]

    operations = [
    ]
