# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_squashed_0005_person_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRMAState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=3)),
                ('customer_rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.CustomerRMA')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_customerrmastate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalRMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=3)),
                ('serial_number', models.CharField(max_length=60, null=True)),
                ('rma_number', models.CharField(max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalRMAState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=3)),
                ('internal_rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.InternalRMA')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_internalrmastate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_rma_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_rma_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='internalrma',
            name='general_rma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.RMA'),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_internalrma_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_internalrma_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerrma',
            name='general_rma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.RMA'),
        ),
        migrations.AddField(
            model_name='customerrma',
            name='original_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='customerrma',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_customerrma_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerrma',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_customerrma_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
