# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_auto_20161001_0227'),
        ('crm', '0001_squashed_0005_person_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRMATask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRMATaskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('customer_rma_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.CustomerRMATask')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_customerrmataskstate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalRMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalRMAState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('internal_rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.InternalRMA')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_internalrmastate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RMACause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectRefundRMA',
            fields=[
                ('rmacause_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rma.RMACause')),
                ('refund_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.RefundTransactionLine')),
            ],
            options={
                'abstract': False,
            },
            bases=('rma.rmacause',),
        ),
        migrations.CreateModel(
            name='StockRMA',
            fields=[
                ('rmacause_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rma.RMACause')),
                ('value_currency', money.models.CurrencyField(max_length=3)),
                ('value', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('rma.rmacause',),
        ),
        migrations.CreateModel(
            name='TestRMA',
            fields=[
                ('rmacause_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rma.RMACause')),
                ('customer_rma_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.CustomerRMATask')),
                ('transaction_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.TransactionLine')),
            ],
            options={
                'abstract': False,
            },
            bases=('rma.rmacause',),
        ),
        migrations.AddField(
            model_name='rmacause',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_rmacause_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmacause',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_rmacause_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='rma_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.RMACause'),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_internalrma_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_internalrma_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
