# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_str', models.CharField(db_index=True, editable=False, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex=re.compile('[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+-]', 32))])),
                ('public', models.BooleanField(default=True)),
                ('sharing_id', models.PositiveIntegerField()),
                ('sharing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
