# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('obj_pk', models.IntegerField()),
                ('to_string', models.CharField(max_length=128)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blame_blamelog_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
