# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blame', '0002_blamelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blamelog',
            name='to_string',
            field=models.CharField(max_length=500),
        ),
    ]
