# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_squashed_0008_auto_20160526_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercosttransactionline',
            name='transactionline_ptr',
        ),
        migrations.RemoveField(
            model_name='othertransactionline',
            name='transactionline_ptr',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='salestransactionline',
            name='article',
        ),
        migrations.RemoveField(
            model_name='salestransactionline',
            name='transactionline_ptr',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='salesperiod',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock_change_set',
        ),
        migrations.RemoveField(
            model_name='transactionline',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='OtherCostTransactionLine',
        ),
        migrations.DeleteModel(
            name='OtherTransactionLine',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SalesTransactionLine',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionLine',
        ),
    ]
