# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160914_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'permissions': (('open_register', 'Can open a register'), ('close_register', 'Can close a register'))},
        ),
    ]
