# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160304_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercount',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=28),
        ),
    ]
