# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160305_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='Missing', max_length=255),
        ),
        migrations.AddField(
            model_name='register',
            name='payment_method',
            field=models.CharField(default='Missing', max_length=255),
        ),
    ]
