# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160305_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_cash_register',
            field=models.BooleanField(default=False),
        ),
    ]
