# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20170426_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercount',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
