# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 21:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_merge'),
        ('article', '0001_initial'),
        ('money', '0006_accountinggroup'),
        ('register', '0007_auto_20160308_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingCountDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_currency', money.models.CurrencyField(max_length=3)),
                ('difference', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningCountDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_currency', money.models.CurrencyField(max_length=3)),
                ('difference', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('register_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterCount')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', money.models.CurrencyField(max_length=3)),
                ('amount', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPeriodDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=28)),
                ('currency_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.CurrencyData')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price_currency', money.models.CurrencyField(max_length=3)),
                ('price_vat', money.models.VATLevelField(decimal_places=6, max_digits=8)),
                ('price', money.models.PriceField(decimal_places=5, max_digits=28, no_currency_field=True, no_vat_field=True)),
                ('count', models.IntegerField()),
                ('isRefunded', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='registerperiod',
            name='memo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesperiod',
            name='closing_memo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='OtherCostTransactionLine',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.TransactionLine')),
            ],
            bases=('register.transactionline',),
        ),
        migrations.CreateModel(
            name='OtherTransactionLine',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.TransactionLine')),
            ],
            bases=('register.transactionline',),
        ),
        migrations.CreateModel(
            name='SalesTransactionLine',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.TransactionLine')),
                ('labeltype', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Labeltype should be longer than zero characters', regex='^.+$')])),
                ('labelkey', models.IntegerField(blank=True, null=True)),
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
            options={
                'abstract': False,
            },
            bases=('register.transactionline', models.Model),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='salesperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock_change_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockChangeSet'),
        ),
        migrations.AddField(
            model_name='salesperioddifference',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Transaction'),
        ),
        migrations.AddField(
            model_name='closingcountdifference',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod'),
        ),
    ]
