# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_merge'),
        ('register', '0008_auto_20160405_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPeriodDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=28)),
                ('currency_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.CurrencyData')),
            ],
        ),
        migrations.AddField(
            model_name='salesperiod',
            name='closing_memo',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='salesperiod',
            name='opening_memo',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='salesperioddifference',
            name='sales_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod'),
        ),
    ]
