# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160413_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperiod',
            name='closing_memo',
        ),
        migrations.AddField(
            model_name='salesperiod',
            name='losing_memo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesperiod',
            name='opening_memo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
