# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20160413_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingCountDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_currency', money.models.CurrencyField(max_length=3)),
                ('difference', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('RegisterPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningCountDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_currency', money.models.CurrencyField(max_length=3)),
                ('difference', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('registerCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegisterCount')),
            ],
        ),
    ]
