# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_closingcountdifference_openingcountdifference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closingcountdifference',
            old_name='RegisterPeriod',
            new_name='register_period',
        ),
        migrations.RenameField(
            model_name='openingcountdifference',
            old_name='registerCount',
            new_name='register_count',
        ),
    ]
