# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20160413_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closingcountdifference',
            name='register_period',
        ),
        migrations.AddField(
            model_name='closingcountdifference',
            name='sales_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.SalesPeriod'),
            preserve_default=False,
        ),
    ]
