# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20160428_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperiod',
            name='opening_memo',
        ),
        migrations.AddField(
            model_name='registerperiod',
            name='memo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
