# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_transaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_created',
        ),
    ]
