# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_squashed_0005_person_user'),
        ('sales', '0004_auto_20160918_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransactionline',
            name='labelkey',
        ),
        migrations.RemoveField(
            model_name='salestransactionline',
            name='labeltype',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
