# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20160920_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stock_change_set',
        ),
    ]
