# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20170621_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercosttransactionline',
            name='other_cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.OtherCostType'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.PaymentType'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Transaction'),
        ),
        migrations.AlterField(
            model_name='priceoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundtransactionline',
            name='sold_transaction_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_line', to='sales.TransactionLine'),
        ),
        migrations.AlterField(
            model_name='refundtransactionline',
            name='test_rma',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rma.TestRMA'),
        ),
        migrations.AlterField(
            model_name='salestransactionline',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='salesperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.SalesPeriod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transaction_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='accounting_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.AccountingGroup'),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='original_price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.PriceOverride'),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Transaction'),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactionline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactionline_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
