# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('O', 'Ordered by Customer'), ('L', 'Ordered at Supplier'), ('A', 'Arrived at Store'), ('C', 'Cancelled'), ('S', 'Sold')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('O', 'Ordered by Customer'), ('L', 'Ordered at Supplier'), ('A', 'Arrived at Store'), ('C', 'Cancelled'), ('S', 'Sold')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('orderline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderLine')),
            ],
        ),
    ]
