# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('A', 'Arrived at Store'), ('C', 'Cancelled'), ('I', 'Used for Internal Purposes'), ('L', 'Ordered at Supplier'), ('O', 'Ordered by Customer'), ('S', 'Sold')], max_length=3)),
                ('expected_sales_price_currency', money.models.CurrencyField(max_length=3)),
                ('expected_sales_price_vat', money.models.VATLevelField(decimal_places=6, max_digits=15)),
                ('expected_sales_price', money.models.PriceField(decimal_places=5, max_digits=28, no_currency_field=True, no_vat_field=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderline_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderline_modified_by', to=settings.AUTH_USER_MODEL)),
                ('wishable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.WishableType')),
            ],
            options={
                'ordering': ['state', 'wishable'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('A', 'Arrived at Store'), ('C', 'Cancelled'), ('I', 'Used for Internal Purposes'), ('L', 'Ordered at Supplier'), ('O', 'Ordered by Customer'), ('S', 'Sold')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('orderline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderLine')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderlinestate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
