# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160617_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='expected_sales_price',
            field=money.models.PriceField(decimal_places=5, default=-1, max_digits=28, no_currency_field=True, no_vat_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='expected_sales_price_currency',
            field=money.models.CurrencyField(default='XXX', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='expected_sales_price_vat',
            field=money.models.VATLevelField(decimal_places=6, default=100, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='state',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='orderlinestate',
            name='state',
            field=models.CharField(max_length=3),
        ),
    ]
