# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 22:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_auto_20160818_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='date_created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 18, 22, 15, 23, 117805, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 18, 22, 15, 38, 865817, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_orderline_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='user_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_orderline_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
