# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20160901_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='state',
            field=models.CharField(choices=[('A', 'Arrived at Store'), ('C', 'Cancelled'), ('I', 'Used for Internal Purposes'), ('L', 'Ordered at Supplier'), ('O', 'Ordered by Customer'), ('S', 'Sold')], max_length=3),
        ),
        migrations.AlterField(
            model_name='orderlinestate',
            name='state',
            field=models.CharField(choices=[('A', 'Arrived at Store'), ('C', 'Cancelled'), ('I', 'Used for Internal Purposes'), ('L', 'Ordered at Supplier'), ('O', 'Ordered by Customer'), ('S', 'Sold')], max_length=3),
        ),
    ]
