# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0005_auto_20161019_1900'),
        ('stock', '0002_stocklock_stocklocklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepancySolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_label', models.CharField(max_length=30, null=True)),
                ('stock_key', models.IntegerField(null=True)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
        ),
        migrations.CreateModel(
            name='StockCountDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('stock_change_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockChangeSet')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_stockcountdocument_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('previous_count', models.IntegerField()),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
                ('physical_count', models.IntegerField()),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_count.StockCountDocument')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_stockcountline_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_stockcountline_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryArticleCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('article_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
        ),
    ]
