# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_squashed_0005_person_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('link_user_to_person', 'Can link Swipe users to Persons'),)},
        ),
    ]
