# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20160329_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone number'),
        ),
    ]
