# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_stockwish_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockWishTableLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(default=0)),
                ('article_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_stockwishtableline_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_stockwishtableline_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockWishTableLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType')),
                ('stock_wish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.StockWish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_supplierorder_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('line_cost_currency', money.models.CurrencyField(max_length=3)),
                ('line_cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('state', models.CharField(max_length=5)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType')),
                ('order_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.OrderLine')),
                ('supplier_article_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.ArticleTypeSupplier')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.SupplierOrder')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_supplierorderline_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_supplierorderline_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=5)),
                ('supplier_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.SupplierOrderLine')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_supplierorderstate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='supplier_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.SupplierOrder'),
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_stockwishtablelog_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
