# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockwishline',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='stockwishline',
            name='stock_wish',
        ),
        migrations.AlterField(
            model_name='stockwishtableline',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StockWishLine',
        ),
    ]
