# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderline',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderLine'),
        ),
    ]
