# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_supplierorderline_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderline',
            name='supplier_article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.ArticleTypeSupplier'),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='supplier_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.SupplierOrder'),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_supplierorderline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_supplierorderline_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_supplierorder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='stock_wish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.StockWish'),
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='supplier_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.SupplierOrder'),
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwishtablelog_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockwishtableline',
            name='article_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
        ),
        migrations.AddField(
            model_name='stockwishtableline',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwishtableline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockwishtableline',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwishtableline_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockwish',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwish_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
