# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 19:01
from __future__ import unicode_literals

from django.db import migrations
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20160819_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderline',
            name='line_cost',
            field=money.models.CostField(decimal_places=5, default=None, max_digits=28, no_currency_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='line_cost_currency',
            field=money.models.CurrencyField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
