# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20160822_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='state',
            field=models.CharField(default='-', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderstate',
            name='supplier_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.SupplierOrderLine'),
        ),
    ]
