# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0004_auto_20160823_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockwish',
            name='copro',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='copro',
        ),
        migrations.AddField(
            model_name='stockwish',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockwish',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwish_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockwishtableline',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockwishtableline',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockwishtableline',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwishtableline_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockwishtableline',
            name='user_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwishtableline_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockwishtablelog',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_stockwishtablelog_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_supplierorder_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_supplierorderline_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='user_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_supplierorderline_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderstate',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierorderstate',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_supplierorderstate_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
