# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160810_2229'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTypeSupplier',
            fields=[
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('minimum_number_to_order', models.IntegerField()),
                ('supplier_string', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('availability', models.CharField(max_length=255)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cost_per_item_currency', money.models.CurrencyField(max_length=3)),
                ('cost_per_item', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('article_type_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.ArticleTypeSupplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTypeArticle',
            fields=[
                ('supplier_string', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='graduationpricing',
            unique_together=set([('article_type_supplier', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='articletypesupplier',
            unique_together=set([('supplier', 'article_type')]),
        ),
    ]
