# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20160929_0748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraduationPricing',
            new_name='VolumeDiscountPricing',
        ),
    ]
