# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20170105_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliertypearticle',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='suppliertypearticle',
            name='supplier_string',
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='article_type_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.ArticleTypeSupplier'),
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='cost',
            field=money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='cost_currency',
            field=money.models.CurrencyField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='ean',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='minimum_number_to_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='packing_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='supply',
            field=models.IntegerField(null=True),
        ),
    ]
