# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_auto_20170116_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypearticle',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliertypearticle',
            name='article_type_supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.ArticleTypeSupplier'),
        ),
    ]
