# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_auto_20170116_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletypesupplier',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suppliertypearticle',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articletypesupplier',
            name='supplier_string',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suppliertypearticle',
            name='article_type_supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.ArticleTypeSupplier'),
        ),
    ]
