# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 01:42
from __future__ import unicode_literals

from django.db import migrations, models


# noinspection PySetFunctionToLiteral
class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20170122_1903'),
    ]

    # noinspection PySetFunctionToLiteral
    operations = [
        migrations.AlterField(
            model_name='articletypesupplier',
            name='availability',
            field=models.CharField(choices=[('A', 'Available at Supplier'), ('D', 'Defunct product'), ('L', 'Later available'), ('U', 'Unknown availability')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='suppliertypearticle',
            unique_together=set([('supplier', 'number')]),
        ),
    ]
