# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplication', '0003_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplication_invoice_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packingdocument',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplication_packingdocument_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packingdocumentline',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='packingdocumentline',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplication_packingdocumentline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packingdocumentline',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplication_packingdocumentline_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='packing_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplication.PackingDocument'),
        ),
    ]
