# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20161019_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='ean',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
