# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_merge_20170202_2145'),
        ('article', '0009_articletype_serial_number'),
    ]

    operations = [
    ]
