# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_merge_20170208_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombination',
            name='and_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.AndProductType'),
        ),
        migrations.AlterField(
            model_name='productcombination',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='sellabletype',
            name='accounting_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.AccountingGroup'),
        ),
    ]
