# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0003_auto_20170426_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentlabel',
            name='label_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='assortment.AssortmentLabelType'),
        ),
        migrations.AlterField(
            model_name='assortmentlabeltype',
            name='unit_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='assortment.AssortmentUnitType'),
        ),
    ]
