# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTypeSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('minimum_number_to_order', models.IntegerField()),
                ('supplier_string', models.CharField(max_length=255)),
                ('availability', models.CharField(choices=[('A', 'Available at Supplier'), ('D', 'Defunct product'), ('L', 'Later available'), ('U', 'Unknown availability')], max_length=255)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier')),
                ('search_url', models.CharField(blank=True, max_length=255, verbose_name='Search URL')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_used', models.BooleanField(default=True, verbose_name='This supplier is used')),
                ('is_backup', models.BooleanField(default=False, verbose_name='This supplier is a backup supplier')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='This supplier is soft-deleted')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTypeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('ean', models.BigIntegerField(null=True)),
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True, null=True)),
                ('minimum_number_to_order', models.IntegerField(null=True)),
                ('supply', models.IntegerField(null=True)),
                ('packing_amount', models.IntegerField(null=True)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('article_type_supplier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.ArticleTypeSupplier')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeDiscountPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cost_per_item_currency', money.models.CurrencyField(max_length=3)),
                ('cost_per_item', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True)),
                ('article_type_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.ArticleTypeSupplier')),
            ],
        ),
        migrations.AddField(
            model_name='articletypesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='volumediscountpricing',
            unique_together=set([('article_type_supplier', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='suppliertypearticle',
            unique_together=set([('supplier', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='articletypesupplier',
            unique_together=set([('supplier', 'article_type')]),
        ),
    ]
