# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20160813_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletypesupplier',
            name='availability',
            field=models.CharField(choices=[('A', 'Available at Supplier'), ('D', 'Defunct product'), ('L', 'Later available'), ('S', 'Soon available'), ('U', 'Unknown availability')], max_length=255),
        ),
    ]
