# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20170105_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTypeArticle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('ean', models.IntegerField(null=True)),
                ('cost_currency', money.models.CurrencyField(max_length=3)),
                ('cost', money.models.CostField(decimal_places=5, max_digits=28, no_currency_field=True, null=True)),
                ('minimum_number_to_order', models.IntegerField(null=True)),
                ('supply', models.IntegerField(null=True)),
                ('packing_amount', models.IntegerField(null=True)),
                ('article_type_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.ArticleTypeSupplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='suppliertypearticle',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='SupplierTypeArticle',
        ),
    ]
