# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_auto_20170116_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierTypeArticle2',
            new_name='SupplierTypeArticle',
        ),
    ]
