# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_auto_20170123_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertypearticle',
            name='ean',
            field=models.BigIntegerField(null=True),
        ),
    ]
