# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20170126_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletypesupplier',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='articletypesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='suppliertypearticle',
            name='article_type_supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.ArticleTypeSupplier'),
        ),
        migrations.AlterField(
            model_name='suppliertypearticle',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='volumediscountpricing',
            name='article_type_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.ArticleTypeSupplier'),
        ),
    ]
