# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRMATask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTaskDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('customer_rma_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.CustomerRMATask')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_customertaskdescription_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_customertaskdescription_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalRMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalRMAState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=3)),
                ('internal_rma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.InternalRMA')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_internalrmastate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RMACause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRMAState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=3)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_testrmastate_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectRefundRMA',
            fields=[
                ('rmacause_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rma.RMACause')),
            ],
            options={
                'abstract': False,
            },
            bases=('rma.rmacause',),
        ),
        migrations.CreateModel(
            name='StockRMA',
            fields=[
                ('rmacause_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rma.RMACause')),
                ('value_currency', money.models.CurrencyField(max_length=3)),
                ('value', money.models.MoneyField(decimal_places=5, max_digits=28, no_currency_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('rma.rmacause',),
        ),
        migrations.CreateModel(
            name='TestRMA',
            fields=[
                ('rmacause_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rma.RMACause')),
                ('state', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
            bases=('rma.rmacause',),
        ),
        migrations.AddField(
            model_name='rmacause',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_rmacause_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmacause',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_rmacause_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='rma_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.RMACause'),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_internalrma_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalrma',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_internalrma_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
