# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrmatask',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='customerrmatask',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Transaction'),
        ),
        migrations.AlterField(
            model_name='customertaskdescription',
            name='customer_rma_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.CustomerRMATask'),
        ),
        migrations.AlterField(
            model_name='customertaskdescription',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_customertaskdescription_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customertaskdescription',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_customertaskdescription_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directrefundrma',
            name='refund_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.RefundTransactionLine'),
        ),
        migrations.AlterField(
            model_name='internalrma',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='internalrma',
            name='rma_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.RMACause'),
        ),
        migrations.AlterField(
            model_name='internalrma',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_internalrma_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalrma',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_internalrma_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalrmastate',
            name='internal_rma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.InternalRMA'),
        ),
        migrations.AlterField(
            model_name='internalrmastate',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_internalrmastate_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rmacause',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_rmacause_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rmacause',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_rmacause_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockrma',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleType'),
        ),
        migrations.AlterField(
            model_name='testrma',
            name='customer_rma_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.CustomerRMATask'),
        ),
        migrations.AlterField(
            model_name='testrma',
            name='transaction_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.TransactionLine'),
        ),
        migrations.AlterField(
            model_name='testrmastate',
            name='test_rma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rma.TestRMA'),
        ),
        migrations.AlterField(
            model_name='testrmastate',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_testrmastate_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
