# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160602_2333'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='wishable',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.WishableType'),
            preserve_default=False,
        ),
    ]
