# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_order_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='copro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
