# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 21:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_orderline_copro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_modified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='copro',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='copro',
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 18, 21, 56, 58, 939121, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlinestate',
            name='date_created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 18, 21, 57, 8, 735, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlinestate',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_orderlinestate_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
