# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20160929_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['state', 'wishable']},
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
