# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20161019_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='final_sales_price',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='final_sales_price_currency',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='final_sales_price_vat',
        ),
    ]
