# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_squashed_0007_othertransactionline_accounting_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundTransactionLine',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.TransactionLine')),
                ('sold_transaction_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_line', to='sales.TransactionLine')),
            ],
            options={
                'abstract': False,
            },
            bases=('sales.transactionline',),
        ),
        migrations.AlterField(
            model_name='othercosttransactionline',
            name='other_cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.OtherCostType'),
        ),
        migrations.AlterField(
            model_name='othertransactionline',
            name='accounting_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.AccountingGroup'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transaction_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
