# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20160918_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
    ]
