# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
        ('sales', '0002_auto_20161001_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundtransactionline',
            name='creates_rma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundtransactionline',
            name='test_rma',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rma.TestRMA'),
        ),
    ]
