# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20170128_2218'),
        ('sales', '0003_auto_20161026_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othertransactionline',
            name='accounting_group',
        ),
        migrations.AddField(
            model_name='transactionline',
            name='accounting_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='money.AccountingGroup'),
            preserve_default=False,
        ),
    ]
