# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 15:07
from __future__ import unicode_literals

from django.db import migrations
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20170208_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionline',
            name='original_price',
            field=money.models.PriceField(blank=True, decimal_places=5, default=None, max_digits=28, no_currency_field=True, no_vat_field=True, null=True),

        ),
        migrations.AddField(
            model_name='transactionline',
            name='original_price_currency',
            field=money.models.CurrencyField(max_length=3, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionline',
            name='original_price_vat',
            field=money.models.VATLevelField(decimal_places=6, max_digits=15, null=True),
            preserve_default=False,
        ),
    ]
