# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_auto_20170208_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('original_price_currency', money.models.CurrencyField(max_length=3)),
                ('original_price_vat', money.models.VATLevelField(decimal_places=6, max_digits=15)),
                ('original_price', money.models.PriceField(decimal_places=5, max_digits=28, no_currency_field=True, no_vat_field=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transactionline',
            name='original_price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.PriceOverride'),
        ),
    ]
